Fix test_verify_tempest_config unit tests
The patch fixes:
AttributeError: 'Manager' object has no attribute 'compute'
thrown by the test_verify_tempest_config unit tests.
The patch edits the failing unit tests so that they use
a mocked Manager instead of the real one.

Closes-Bug: #1918407
Change-Id: I1fcce1ebba61ba33b1e948a80cb572f8ae17c548
(cherry picked from commit 11a3e06c5f3a16bb83e1a34951c01613b1124824)